import type { Menu } from "./types";

export const menus: Menu[] = [
  {
    id_menu: "menu-dashboard",
    nama_menu: "Dashboard",
    kode_menu: "dashboard",
    icon: "LayoutDashboard",
    path: "/dashboard",
    urutan: 1,
    is_active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id_menu: "menu-barang",
    nama_menu: "Data Barang",
    kode_menu: "barang",
    icon: "Package",
    path: "/barang",
    urutan: 2,
    is_active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id_menu: "menu-transaksi",
    nama_menu: "Transaksi",
    kode_menu: "transaksi",
    icon: "ShoppingCart",
    path: "/transaksi",
    urutan: 3,
    is_active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id_menu: "menu-stok",
    nama_menu: "Stok",
    kode_menu: "stok",
    icon: "Boxes",
    path: "/stok",
    urutan: 4,
    is_active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id_menu: "menu-laporan",
    nama_menu: "Laporan",
    kode_menu: "laporan",
    icon: "FileText",
    path: "/laporan",
    urutan: 5,
    is_active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id_menu: "menu-pengguna",
    nama_menu: "Pengguna",
    kode_menu: "pengguna",
    icon: "Users",
    path: "/pengguna",
    urutan: 6,
    is_active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id_menu: "menu-hak-akses",
    nama_menu: "Hak Akses",
    kode_menu: "hak_akses",
    icon: "ShieldCheck",
    path: "/api/v1/hak-akses",
    urutan: 7,
    is_active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];